name: Block direct push to main
on:
  push:
    branches: [main]

jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel if commit is from a Pull Request Merge
        if: |
          startsWith(github.event.head_commit.message, 'Merge pull request')
        run: |
          echo "This push was from a PR merge. Exiting block."
          exit 0

      - name: Block direct psuhes to main
        run: |
          echo "Direct push to main is not allowed. Please use Pull Requests."
          exit 1
