# .github/workflows/docker-publish.yml

name: Publish Docker Image

# Trigger on new version tags (created by semantic-release)
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read       # for checkout
  packages: write      # to push to GHCR
  id-token: write      # if using OIDC

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo (with full history so semantic-release tags exist)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Set up Docker Buildx (for multi-platform if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Extract version from package.json
      - name: Extract version
        id: meta
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 5. Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mikeholownych/mcp:${{ steps.meta.outputs.version }}
            ghcr.io/mikeholownych/mcp:latest
