name: Release

# Run on every push to main
on:
  push:
    branches:
      - main

# Grant the minimum scopes for tagging, releases & packages
permissions:
  contents: write    # allow pushing commits & tags
  packages: write    # allow publishing packages (if used)
  pull-requests: write
  issues: write      # for @semantic-release/github

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0         # <-- fetch all tags
          persist-credentials: true  # <-- allow GITHUB_TOKEN to persist

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
